### ISSUE TITLE
Issue with tensor size by running with yolov3

### ISSUE THREAD

**Issue by danieldd2** [DC1991/FS-Net#16]
Hi thanks for the repo.

Can you please help me with the current issue. I try to run the detect_fsnet.py tutorial and i get an error with yolov3 and yolov5 model in yolo,py (line 57, in forward)

RuntimeError: The size of tensor a (40) must match the size of tensor b (44) at non-singleton dimension 3

I try to exchange the yolov3 files with the new version from the yolov3 repo but they are to different.

**Comment by danieldd2** [comment]
I could fix it by exchanging the code

**Comment by LZzzin1** [comment]
how? i have same error

**Comment by tauuuuuuu** [comment]
how to exchange the code
